spring:
  application:
    name: TaskManagementSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/schema.sql

---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager_test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/schema.sql
      data-locations: classpath:db/migration/test-data.sql

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG