spring:
  application:
    name: TaskManagementSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true


  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    postgresql-username: ${spring.datasource.username}
    postgresql-password: ${spring.datasource.password}
    baseline-version: 0
    clean-disabled: false # Enable only for development!

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager_test
    username: postgres
    password: postgres

  flyway:
    clean-on-validation-error: true
    clean-disabled: false